sudo: false
language: node_js
node_js:
- 8
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  api_key:
    secure: R87miNK7LpCitqMHiKXcONyc1wMMqfH2BpUn428D9SbCVp7iz9a/1Xz+qJ4jc+NpO6e0fLgafYeh8CJZ8+JV47lRIm/tpKQxtOPrPqGycc9M3LXPlBb7QYRBceoZq/DdhKATQulEo/PM+D4ykSwSy7zRIoG7CvnA0Clbsb8HTuO4F74i5WNkyIfFsCZaMpw9GjbKjpSu8PdtTAewIQRDOe7cD5+b4d81yQAlUOm6Kxqzus8bgm/C5zQk3tbPb8WENdcE7dny8SnowJEWELeuzRTAOHrYP/ahOBLIG7Ou3IIuiJZHOwxvIU0BLpuZoqQwi5c6nKFCGd8rldb4kMdeRFnEpdgQ1x5TfLfqsmbTqq/rxbWnd77TXOakRXhycAjZSMI3M7L19wTKbpr+Wk23PNUbZF6DB5lHhSAUYsz6OL+MYAr50guNJ5phrnFE+U45V4Xx6yLVKEbWaHmr+OWsAaQfKPrxy9Pd9Ox2ZUY08sAFTNRTLVBnhDSp1Q6fdS+wZ+EnIt6P02nyBZvdePTLVvq1w2cNmXshDwiEeFdzRWmd+8jlLFyHAGE6dTl9ZsboZou2+kgbB47RZkchbsefudyW8792CJPNuN3PASx3NU6YOTpNic2jwHLKcI8/b650QSkr6rXfD/wkXekf5tkqB33FgpSpTSBZ+MihaS6rG30=
  on:
    tags: true
    branch: master
